spring:
  application:
    name: spring-ai-agent-tutorial
  main:
    web-application-type: none
  shell:
    interactive:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 300000
            read-timeout: 300000

  ai:
    model:
      chat: openai
      embedding: ollama

    openai:
      # DeepSeek использует OpenAI-совместимый API
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 3000

    ollama:
      base-url: http://localhost:11432
      embedding:
        model: mxbai-embed-large
        options:
          temperature: 0.7

    vectorstore:
      simple:
        enabled: true

spring-ai-agent-sandbox:
  integration:
    tg-chats-collector:
      host: http://localhost:8083

logging:
  level:
    root: INFO
    ru.panyukovnn: DEBUG
    org.springframework.ai: DEBUG